import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../../domain/entities/farmer_profile_entity.dart';
import '../../domain/entities/product_entity.dart';
import '../../domain/entities/order_entity.dart';
import '../../domain/usecases/profile_usecases.dart';
import '../../domain/usecases/product_usecases.dart';
import '../../domain/usecases/order_usecases.dart';

class FarmerViewModel extends ChangeNotifier {
  final CreateFarmerProfileUseCase _createFarmerProfileUseCase;
  final GetFarmerProductsUseCase _getFarmerProductsUseCase;
  final CreateProductUseCase _createProductUseCase;
  final DeleteProductUseCase _deleteProductUseCase;
  final GetFarmerOrdersUseCase _getFarmerOrdersUseCase;
  final UpdateOrderStatusUseCase _updateOrderStatusUseCase;

  FarmerViewModel({
    required CreateFarmerProfileUseCase createFarmerProfileUseCase,
    required GetFarmerProductsUseCase getFarmerProductsUseCase,
    required CreateProductUseCase createProductUseCase,
    required DeleteProductUseCase deleteProductUseCase,
    required GetFarmerOrdersUseCase getFarmerOrdersUseCase,
    required UpdateOrderStatusUseCase updateOrderStatusUseCase,
  })  : _createFarmerProfileUseCase = createFarmerProfileUseCase,
        _getFarmerProductsUseCase = getFarmerProductsUseCase,
        _createProductUseCase = createProductUseCase,
        _deleteProductUseCase = deleteProductUseCase,
        _getFarmerOrdersUseCase = getFarmerOrdersUseCase,
        _updateOrderStatusUseCase = updateOrderStatusUseCase;

  List<ProductEntity> _myProducts = [];
  List<OrderEntity> _myOrders = [];
  bool _isLoading = false;
  String? _errorMessage;

  List<ProductEntity> get myProducts => _myProducts;
  List<OrderEntity> get myOrders => _myOrders;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  // Stats
  int get todayOrdersCount {
    final now = DateTime.now();
    return _myOrders.where((o) => 
      o.createdAt.year == now.year &&
      o.createdAt.month == now.month &&
      o.createdAt.day == now.day
    ).length;
  }

  double get todayEarnings {
    final now = DateTime.now();
    return _myOrders.where((o) => 
      o.createdAt.year == now.year &&
      o.createdAt.month == now.month &&
      o.createdAt.day == now.day &&
      o.status != 'cancelled'
    ).fold(0.0, (sum, o) => sum + o.totalAmount);
  }

  List<ProductEntity> get recentProducts => _myProducts.take(3).toList();

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }

  void _setError(String? message) {
    _errorMessage = message;
    notifyListeners();
  }

  // Create Farmer Profile
  Future<bool> createProfile({
    required String id,
    required String name,
    required String phone,
    required String village,
    required String district,
    required String state,
    required String pincode,
    required double farmSize,
    required List<String> products,
    XFile? imageFile,
  }) async {
    _setLoading(true);
    _setError(null);
    try {
      final profile = FarmerProfileEntity(
        id: id,
        farmerId: '', // Database trigger generates this
        name: name,
        phone: phone,
        village: village,
        district: district,
        state: state,
        pincode: pincode,
        farmSize: farmSize,
        products: products,
        createdAt: DateTime.now(),
      );

      await _createFarmerProfileUseCase(profile, imageFile);
      _setLoading(false);
      return true;
    } catch (e) {
      _setError(e.toString());
      _setLoading(false);
      return false;
    }
  }

  // Fetch Farmer Products & Orders
  Future<void> fetchDashboardData(String farmerId) async {
    _setLoading(true);
    _setError(null);
    try {
      _myProducts = await _getFarmerProductsUseCase(farmerId);
      _myOrders = await _getFarmerOrdersUseCase(farmerId);
      _setLoading(false);
    } catch (e) {
      _setError(e.toString());
      _setLoading(false);
    }
  }

  // Add Product
  Future<bool> addProduct({
    required String farmerId,
    required String name,
    required String category,
    required double quantity,
    required String unit,
    required double price,
    required String description,
    required DateTime harvestDate,
    XFile? imageFile,
  }) async {
    _setLoading(true);
    _setError(null);
    try {
      final product = ProductEntity(
        id: '', // Generated by Supabase
        farmerId: farmerId,
        name: name,
        category: category,
        quantity: quantity,
        unit: unit,
        price: price,
        description: description,
        harvestDate: harvestDate,
        createdAt: DateTime.now(),
      );

      await _createProductUseCase(product, imageFile);
      // Reload products
      _myProducts = await _getFarmerProductsUseCase(farmerId);
      _setLoading(false);
      return true;
    } catch (e) {
      _setError(e.toString());
      _setLoading(false);
      return false;
    }
  }

  // Delete Product
  Future<bool> removeProduct(String id, String farmerId) async {
    _setLoading(true);
    _setError(null);
    try {
      await _deleteProductUseCase(id);
      _myProducts = await _getFarmerProductsUseCase(farmerId);
      _setLoading(false);
      return true;
    } catch (e) {
      _setError(e.toString());
      _setLoading(false);
      return false;
    }
  }

  // Update Order Status
  Future<bool> updateStatus(String orderId, String status, String farmerId) async {
    _setLoading(true);
    _setError(null);
    try {
      await _updateOrderStatusUseCase(orderId, status);
      _myOrders = await _getFarmerOrdersUseCase(farmerId);
      _setLoading(false);
      return true;
    } catch (e) {
      _setError(e.toString());
      _setLoading(false);
      return false;
    }
  }
}
